/**
 * Crypto parity tests — prove the CLI decrypts vaults exactly like the web app.
 *
 * Fixture provenance (see src/fixtures/*.json `_provenance`):
 * - `parity-vectors.json` captured in real chromium against the real
 *   argon2-browser WASM bundle (fixture-gen/serve/runner.js mirrors crypto.js
 *   byte-for-byte). Per RT-3 these vectors are NOT generated by hash-wasm —
 *   decrypting the AES envelopes with a hash-wasm-derived key only succeeds
 *   if that key is byte-identical to the browser-derived one.
 * - `otp-vectors.json` generated by the PHP server stack
 *   (spomky-labs/otphp + steam-totp — the authoritative implementations
 *   TwoFAccount.php:515-536 delegates to).
 */
import { describe, it, expect } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import {
    deriveKey,
    importAesKey,
    decryptSecret,
    verifyTestValue,
    bytesToBase64,
    base64ToBytes,
    CRYPTO_PARAMS,
    VERIFICATION_TEST_VALUE,
    type SecretEnvelope,
} from '../crypto.js';

const vectorsDir = join(import.meta.dir, '..', '..', 'fixtures');
const parityVectors = JSON.parse(readFileSync(join(vectorsDir, 'parity-vectors.json'), 'utf8')) as {
    argon2_raw: { password: string; saltB64: string; hashHex: string }[];
    aes_envelopes: { password: string; saltB64: string; plaintext: string; envelope: SecretEnvelope }[];
};

function toHex(bytes: Uint8Array): string {
    return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

// Argon2id at 64 MiB costs ~1s per derivation — derive each unique
// (password, salt) once and share across the parity assertions.
const keyCache = new Map<string, Promise<Uint8Array>>();
function deriveCached(password: string, saltB64: string): Promise<Uint8Array> {
    const cacheKey = `${password}|${saltB64}`;
    let key = keyCache.get(cacheKey);
    if (!key) {
        key = deriveKey(password, saltB64);
        keyCache.set(cacheKey, key);
    }
    return key;
}

describe('deriveKey parity with argon2-browser (browser-captured vectors)', () => {
    for (const vector of parityVectors.argon2_raw) {
        it(`matches browser-derived hash for "${vector.password}" / salt ${vector.saltB64.slice(0, 8)}…`, async () => {
            const key = await deriveCached(vector.password, vector.saltB64);
            expect(key.length).toBe(CRYPTO_PARAMS.ARGON2.hashLength);
            expect(toHex(key)).toBe(vector.hashHex);
        }, 30_000);
    }
});

describe('decryptSecret parity (browser-captured AES-GCM envelopes)', () => {
    for (const vector of parityVectors.aes_envelopes) {
        it(`decrypts envelope for "${vector.password}" to "${vector.plaintext.slice(0, 24)}"`, async () => {
            const key = await importAesKey(await deriveCached(vector.password, vector.saltB64));
            expect(await decryptSecret(vector.envelope, key)).toBe(vector.plaintext);
        }, 30_000);
    }

    it('throws the generic web-app error on a wrong password (no oracle)', async () => {
        const vector = parityVectors.aes_envelopes[0];
        const wrongKey = await importAesKey(await deriveKey('definitely-wrong', vector.saltB64));
        expect(decryptSecret(vector.envelope, wrongKey)).rejects.toThrow(
            'Decryption failed: Invalid password or corrupted data',
        );
    }, 30_000);

    it('throws the generic web-app error on tampered ciphertext', async () => {
        const vector = parityVectors.aes_envelopes[0];
        const key = await importAesKey(await deriveCached(vector.password, vector.saltB64));
        const bytes = base64ToBytes(vector.envelope.ciphertext);
        bytes[0] ^= 0x01;
        const tampered = { ...vector.envelope, ciphertext: bytesToBase64(bytes) };
        expect(decryptSecret(tampered, key)).rejects.toThrow('Decryption failed');
    }, 30_000);

    it('rejects a truncated envelope cleanly', async () => {
        const vector = parityVectors.aes_envelopes[0];
        const key = await importAesKey(await deriveCached(vector.password, vector.saltB64));
        const truncated = { ciphertext: '', iv: vector.envelope.iv, authTag: vector.envelope.authTag };
        expect(decryptSecret(truncated, key)).rejects.toThrow('Decryption failed');
    }, 30_000);

    it('rejects malformed base64 cleanly', async () => {
        const vector = parityVectors.aes_envelopes[0];
        const key = await importAesKey(await deriveCached(vector.password, vector.saltB64));
        const malformed = { ...vector.envelope, ciphertext: '!!!not-base64!!!' };
        expect(decryptSecret(malformed, key)).rejects.toThrow('Decryption failed');
    }, 30_000);
});

describe('vault test-value verification', () => {
    it('verifies the sealed VERIFICATION_TEST_VALUE envelope with the correct key', async () => {
        const vector = parityVectors.aes_envelopes.find((v) => v.plaintext === VERIFICATION_TEST_VALUE);
        expect(vector).toBeDefined();
        const key = await importAesKey(await deriveCached(vector!.password, vector!.saltB64));
        expect(await verifyTestValue(JSON.stringify(vector!.envelope), key)).toBe(true);
    }, 30_000);

    it('returns false (never throws) with a wrong key', async () => {
        const vector = parityVectors.aes_envelopes.find((v) => v.plaintext === VERIFICATION_TEST_VALUE)!;
        const wrongKey = await importAesKey(await deriveKey('wrong-password-123', vector.saltB64));
        expect(await verifyTestValue(JSON.stringify(vector.envelope), wrongKey)).toBe(false);
    }, 30_000);

    it('returns false on malformed test-value JSON', async () => {
        const vector = parityVectors.aes_envelopes[0];
        const key = await importAesKey(await deriveCached(vector.password, vector.saltB64));
        expect(await verifyTestValue('not-json', key)).toBe(false);
    }, 30_000);
});
